### ISSUE TITLE
pozycjonowanie div'ów na stronie

### ISSUE THREAD

**Issue by Kruszewski** [SLOths4/DoDomuDojade#56]
Chodzi o to, żeby zadbać o utrzymanie właściwych pozycji elementów na stronie.

Może to trzeba zrobić z tym:
```css
.container {
    display: grid;
    width: 800px;  /* Stała szerokość */
    height: 600px; /* Opcjonalnie */
    grid-template-columns: 200px 400px 200px; /* Trzy kolumny */
    grid-template-rows: 100px 200px 300px;   /* Trzy rzędy */
    gap: 10px; /* Odstępy */
}

.element1 {
    grid-column: 1 / 2; /* Pierwsza kolumna */
    grid-row: 1 / 2;    /* Pierwszy rząd */
}

.element2 {
    grid-column: 2 / 3;
    grid-row: 2 / 3;
}

.element3 {
    grid-column: 3 / 4;
    grid-row: 3 / 4;
}

```
